services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    lindesbs\minkorrekt\Interface\WebscraperPaperDecoderInterface:
      tags: [ 'app.WebscraperPaperDecoderInterface' ]

    lindesbs\minkorrekt\Interface\WebscraperPublisherDecoderInterface:
      tags: [ 'app.WebscraperPublisherDecoderInterface' ]

  lindesbs\minkorrekt\:
    resource: ../../
    exclude: ../../{Entity,Migrations,Model,Resources,Tests,Widget}

  lindesbs.minkorrekt.websitescraperpaper:
    class: lindesbs\minkorrekt\Service\WebsiteScraperPaper
    public: true

  lindesbs.minkorrekt.websitescraperpublisher:
    class: lindesbs\minkorrekt\Service\WebsiteScraperPublisher
    public: true

  lindesbs.minkorrekt.generatestatistics:
    class: lindesbs\minkorrekt\Service\GenerateStatistics
    public: true
    tags:

  lindesbs\minkorrekt\Factory\WebscraperPaperDecoderFactory:
    arguments:
      $importer: !tagged_iterator 'app.WebscraperPaperDecoderInterface'

  lindesbs\minkorrekt\Factory\WebscraperPublisherDecoderFactory:
    arguments:
      $importer: !tagged_iterator 'app.WebscraperPublisherDecoderInterface'

