services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    lindesbs\minkorrekt\Interface\WebscraperItemdecoderInterface:
      tags: [ 'app.WebscraperItemdecoderInterface' ]

  lindesbs\minkorrekt\:
    resource: ../../
    exclude: ../../{Entity,Migrations,Model,Resources,Tests,Widget}

  lindesbs.minkorrekt.websitescrape:
    class: lindesbs\minkorrekt\Service\WebsiteScraper
    public: true

  lindesbs.minkorrekt.generatestatistics:
    class: lindesbs\minkorrekt\Service\GenerateStatistics
    public: true
    tags:

  lindesbs\minkorrekt\Factory\WebscraperItemdecoderFactory:
    arguments:
      $importer: !tagged_iterator 'app.WebscraperItemdecoderInterface'

