services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  lindesbs\minkorrekt\:
    resource: ../../
    exclude: ../../{Entity,Migrations,Model,Resources,Tests,Widget}

  lindesbs.minkorrekt.websitescrape:
    class: lindesbs\minkorrekt\Service\WebsiteScraper
    public: true